package:
  name: "adcme-gpu"
  version: "0.1.0"

build:
    number: '0'
    string: py37gpu
    
requirements:
  run:
    - tensorflow-gpu 1.15.* 
    - cudatoolkit 10.0.130 0
    - cudnn 7.6.4 cuda10.0_0
    - cupti 10.0.130 0          

about:
    description: 'ADCME-GPU provides GPU dependencies for GPU acceleration: cudatoolkit, cudnn and cupti'
    dev_url: "https://github.com/kailaix/ADCME.jl"
    doc_source_url: "https://github.com/kailaix/ADCME.jl/docs"
    doc_url: "https://kailaix.github.io/ADCME.jl/dev/"
    home: https://github.com/kailaix/ADCME.jl
    license: MIT
    license_family: MIT
    summary: "ADCME-GPU provides GPU dependencies for GPU acceleration: cudatoolkit, cudnn and cupti"

extra:
  recipe-maintainers:
    - kailaix
