package:
  name: "adcme"
  version: "0.1.0"

build:
    number: '0'
    string: py37cpu
    
requirements:
  run:
    - mkl-service                        [win]
    - make                               [not win]
    - unzip                              [not win]
    - hdf5                               [not linux]
    - tensorflow 1.15.* *py37*
    - tensorflow-probability 0.8
    - matplotlib 
    - openblas                           [not win]
    - _libgcc_mutex 0.1 main             [linux]
    - gcc_linux-64 5.4.0 h98af8de_24     [linux]
    - gcc_impl_linux-64 5.4.0 habb00fd_3 [linux]
    - gxx_impl_linux-64 5.4.0 hdf63c60_3 [linux]
    - gxx_linux-64 5.4.0 h98af8de_24     [linux]
    - libgcc-ng 9.1.0 hdf63c60_0         [linux]
    - libstdcxx-ng 9.1.0 hdf63c60_0      [linux]
    - cctools 895 1                      [osx]
    - clang 4.0.1 1                      [osx]
    - clang_osx-64 4.0.1 h1ce6c1d_18     [osx]
    - clangxx 4.0.1 1                    [osx]
    - clangxx_osx-64 4.0.1 h22b1bf0_18   [osx]
    - compiler-rt 4.0.1 hcfea43d_1       [osx]
    - ld64 274.2 1                       [osx]
    - libcxx 4.0.1 hcfea43d_1            [osx]
    - libcxxabi 4.0.1 hcfea43d_1         [osx]
    - llvm 4.0.1 1                       [osx]
    - llvm-lto-tapi 4.0.1 1              [osx]

about:
    description: 'ADCME is a Julia library for automatic differentiation in scientific computing. It is a powerful tool to combine the best of the two world--machine learning techniques and scientific computing--for data driven inverse problems. Currently, it is only tested on Linux and MacOSX.'
    dev_url: "https://github.com/kailaix/ADCME.jl"
    doc_source_url: "https://github.com/kailaix/ADCME.jl/docs"
    doc_url: "https://kailaix.github.io/ADCME.jl/dev/"
    home: https://github.com/kailaix/ADCME.jl
    license: MIT
    license_family: MIT
    summary: "This package provides the necessary backend for ADCME.jl."

extra:
  recipe-maintainers:
    - kailaix
