name: QuickBuild

on:
  schedule:
    - cron: '00 00 * * *'
  push:
    branches:
      - '*'
    tags: '*'

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Build-Linux
        run: julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("ADCME"); using ADCME'
  MaxOX:
    runs-on: macos-latest
    steps:
      - name: Build-Macos
        run: julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("ADCME"); using ADCME'
  Windows:
    runs-on: windows-latest
    steps:
      - name: Build-Windows
        run: julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("ADCME"); using ADCME'